import React from 'react';
import { View, Text, Pressable, StyleSheet, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By downloading, installing, or using the AesthetiQ application ("App"), you agree to be bound by these Terms & Conditions. If you do not agree, please do not use the App.',
  },
  {
    title: '2. Nature of the Service',
    body: 'AesthetiQ provides AI-powered screening and health monitoring tools for skin and dental health. The App is not a medical device and does not provide medical diagnoses, medical advice, or treatment plans.\n\nAll results, scores, and reports generated by the App are for informational and educational purposes only. They should not be used as a substitute for professional medical advice, diagnosis, or treatment.',
  },
  {
    title: '3. Medical Disclaimer',
    body: 'Always consult a qualified healthcare provider before making any health-related decisions. AesthetiQ and its affiliates are not liable for any health decisions made based on the App\'s output.\n\nIf you are experiencing a medical emergency, contact your local emergency services immediately.',
  },
  {
    title: '4. User Eligibility',
    body: 'You must be at least 18 years of age to use this App. By using the App, you confirm that you meet this requirement. Users under 18 may use the App only with parental or guardian consent.',
  },
  {
    title: '5. Account Responsibility',
    body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorised use at support@aesthetiq.in.',
  },
  {
    title: '6. Payments & Refunds',
    body: 'Certain features, including full AI report unlocks, require a one-time payment. All payments are processed securely via Razorpay.\n\nRefunds are available within 48 hours of purchase if the report could not be generated due to a technical error on our side. Contact support@aesthetiq.in with your transaction ID.',
  },
  {
    title: '7. Intellectual Property',
    body: 'All content, AI models, UI designs, logos, and trademarks within the App are the exclusive property of AesthetiQ Technologies Pvt. Ltd. You may not reproduce, distribute, or create derivative works without explicit written permission.',
  },
  {
    title: '8. Prohibited Use',
    body: 'You agree not to:\n• Use the App for any unlawful purpose\n• Attempt to reverse-engineer or extract the AI models\n• Upload images of other individuals without their consent\n• Circumvent any payment or access control mechanisms\n• Transmit malicious code or interfere with App functionality',
  },
  {
    title: '9. Limitation of Liability',
    body: 'To the maximum extent permitted by law, AesthetiQ shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App, including but not limited to loss of data, health decisions made based on App output, or service interruptions.',
  },
  {
    title: '10. Changes to Terms',
    body: 'We may update these Terms from time to time. We will notify you of significant changes via the App or registered email. Continued use of the App after changes constitutes acceptance of the new Terms.',
  },
  {
    title: '11. Governing Law',
    body: 'These Terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka.',
  },
  {
    title: '12. Contact',
    body: 'For any questions about these Terms, contact us at:\n\nAesthetiQ Technologies Pvt. Ltd.\nsupport@aesthetiq.in',
  },
];

export default function TermsScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <ScrollView showsVerticalScrollIndicator={false}>

        <LinearGradient colors={['#374151', '#6B7280']} style={styles.header}>
          <View style={styles.headerTop}>
            <Pressable onPress={() => router.back()} style={styles.backBtn}>
              <Text style={styles.backArrow}>‹</Text>
            </Pressable>
            <Text style={styles.headerTitle}>📄 Terms & Conditions</Text>
            <View style={{ width: 40 }} />
          </View>
          <Text style={styles.headerSub}>Last updated: April 2025</Text>
        </LinearGradient>

        <View style={styles.body}>
          <Text style={styles.intro}>
            Please read these Terms & Conditions carefully before using AesthetiQ.
          </Text>

          {SECTIONS.map((s) => (
            <View key={s.title} style={styles.section}>
              <Text style={styles.sectionTitle}>{s.title}</Text>
              <Text style={styles.sectionBody}>{s.body}</Text>
            </View>
          ))}

          <View style={{ height: 60 }} />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F2F2F7' },

  header:    { paddingBottom: 20, paddingHorizontal: 20, paddingTop: 0 },
  headerTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 12, marginBottom: 6 },
  backBtn:   { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  backArrow: { fontSize: 28, color: '#fff' },
  headerTitle:{ fontSize: 17, fontWeight: '800', color: '#fff' },
  headerSub:  { fontSize: 13, color: 'rgba(255,255,255,0.75)', textAlign: 'center' },

  body:  { paddingHorizontal: 20, paddingTop: 16 },
  intro: { fontSize: 14, color: '#636366', lineHeight: 22, marginBottom: 20 },

  section:      { marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: '#1C1C1E', marginBottom: 6 },
  sectionBody:  { fontSize: 14, color: '#636366', lineHeight: 22 },
});
